name: testudines_solfago
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  flame: 1.12.0
  flame_audio: ^2.1.5
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flame_lint: 1.1.2
  flame_test: 1.15.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets: 
    - assets/images/
    - assets/audio/